version: '3'

tasks:
  build:
    cmds:
      - rm -rf ./dist
      - mkdir ./dist
      - cp -r ./filestorage ./dist/filestorage
      - cp ./package.json ./dist/package.json
      - cp ./README.md ./dist/README.md
  publish:
    cmd: npm publish ./dist --access public